class DummyModel:
    # dummy high risk 0
    # dummy high risk 1
    # dummy high risk 2
    # dummy high risk 3
    # dummy high risk 4
    # dummy high risk 5
    # dummy high risk 6
    # dummy high risk 7
    # dummy high risk 8
    # dummy high risk 9
    # dummy high risk 10
    # dummy high risk 11
    # dummy high risk 12
    # dummy high risk 13
    # dummy high risk 14
    # dummy high risk 15
    # dummy high risk 16
    # dummy high risk 17
    # dummy high risk 18
    # dummy high risk 19
    # dummy high risk 20
    # dummy high risk 21
    # dummy high risk 22
    # dummy high risk 23
    # dummy high risk 24